### ISSUE TITLE
Updated web-ifc and web-ifc-three versions

### ISSUE THREAD

**Issue by khuongtran78** [chuongmep/ifcjs-rollup#1]
Hi,

Thanks for the repo! I have a question: can we update the package.json to get the latest version of web-ifc and web-ifc-three? I cannot resolve the version conflicts so always end up using web-ifc v0.0.33

Thank you

**Comment by chuongmep** [comment]
Hi khuong, 

I updated bun and dependency to latest. In the case you want follow all updated  of IFC, 
LIBRARY [web-ifc-three](https://github.com/IFCjs/web-ifc-three) IS DEPRECATED. USE [COMPONENTS](https://github.com/ifcjs/components) INSTEAD
They changed to component from end of last year : https://github.com/IFCjs/components

**Comment by chuongmep** [comment]
In the case you need update by your self : 
``` bash
bun install web-ifc
bun install web-ifc-three
```
